config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  devise_for :users

  namespace :prototypes do #rails g controller prototypes/users
    resources :users, only: [:edit, :update, :show]
    resources :newest, only: [:index]
    resources :popular, only: [:index]
  end

  resources :prototypes
  resources :tags, only: [:index, :show]
  resources :comments, only: [:new, :create]
  resources :likes, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  has_many :thumbnails
  has_many :likes
  has_many :comments
  belongs_to :user

  #ページネーション
  paginates_per 12

  #バリデーション（値がからでないか）
  validates_presence_of :title, :catchcopy, :concept

  #fields_for(formのネスト)
  accepts_nested_attributes_for :thumbnails

  #liked_by?というメソッドはそのユーザが、アクセスしている投稿にlikeをしているかどうかというものを判定するものです。
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  # acts_as_taggable_on :tags のエイリアス
  acts_as_taggable
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user

  # carrierwave
  mount_uploader :image, AvatarUploader
  enum status: %i(main sub)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prototypes
  has_many :likes
  has_many :comments
  has_many :thumbnails

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :avatar, :member, :profile, :works)
    devise_parameter_sanitizer.for(:account_update).push(:name, :avatar, :member, :profile, :works)
    #devise_parameter_sanitizer.for(:sign_up) << [:name, :avatar, :member, :profile, :works]
  end

  def after_sign_out_path_for(resource)#ログアウトしたらサインインにリダイレクト
    user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    current_user.comments.create(comment_params)
    @prototype = Prototype.find(comment_params[:prototype_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :prototype_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user.likes.create(prototype_id: params[:id])
    @prototype = Prototype.find(params[:id])
  end
  def destroy
    current_user.likes.find_by(prototype_id: params[:id]).destroy
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.order(created_at: :DESC).page(params[:page])
    #render 'top/index' #これがないとnewestコントローラー配下を見に行っちゃうので必要
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.order(likes_count: :DESC).page(params[:page])
    #render "top/index"
  end
end

app/controllers/prototypes/users_controller.rb
class Prototypes::UsersController < ApplicationController
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def show
    @prototype = Prototype.includes(:user, :thumbnails).find(params[:id])
    @prototype_image = @prototype.thumbnails.main.first.image

    @new_comment = Comment.new
    @comments = @prototype.comments
  end

  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    Prototype.find(params[:id]).update(update_params)
    redirect_to root_path
  end

  def destroy
    prototype = Prototype.find(params[:id])
    if prototype.user_id == current_user.id
      prototype.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catchcopy, :concept, thumbnails_attributes: [:image, :status]).merge(tag_list: params[:prototype][:tag])
  end

  def update_params
    params.require(:prototype).permit(:title, :catchcopy, :concept, thumbnails_attributes: [:id, :image, :status]).merge(user_id: current_user.id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = params[:id]
    @prototypes = Prototype.tagged_with(@tag).page(params[:page])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @prototypes = Prototype.page(params[:page]).order(id: :DESC)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_user!, only: [:show]

  def show
    @user = User.includes(:prototypes).find(params[:id])
    @prototypes = @user.prototypes.page(params[:page])
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :works, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag(@prototype.user.avatar), prototypes_user_path(comment.user_id), class: "media-object", alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", style: "width: 64px; height: 64px;"
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      = link_to "#top-aligned-media", class: "anchorjs-link" do
        %span.anchorjs-icon
    %p
      = comment.comment

app/views/comments/create.js.erb
$(".form-control").val("");
$("#comments").html(
  '<%= j(render partial: 'comments/comment', collection: @prototype.comments) %>'
);

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - unless user_signed_in?
        //not login
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Sign In', new_user_session_path
      - else
        //login
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'My Page', prototypes_user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_registration_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
.col-md-6.text-right
  - if @prototype.liked_by?(current_user) #if current_user.likes.exists?
    %button.btn.btn-default
      = link_to image_tag('icon_heart_red.svg'), like_path(@prototype), method: :delete, remote: true
      / = link_to image_tag('icon_heart_red.svg'), like_path(prototype_id: @prototype.id), method: :delete, remote: true
      Like
      %span.num= @prototype.likes_count
  - else
    %button.btn.btn-default
      = link_to image_tag('icon_heart.svg'), likes_path(id: @prototype.id), method: :post, remote: true
      / = link_to image_tag('icon_heart.svg'), likes_path(prototype_id: @prototype.id), method: :post, remote: true
      Like
      %span.num= @prototype.likes_count

app/views/likes/create.js.erb
$('#like_box').html(
   '<%= j(render partial: 'likes/like') %>'
  );

app/views/likes/destroy.js.erb
$('#like_box').html(
   '<%= j(render partial: 'likes/like') %>'
  );

app/views/prototypes/edit.html.haml
= form_for @prototype, html: {class: 'container proto-new'} do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: 'proto-new-title'
    .row
      .col-md-12
        .cover-image-upload
          = f.fields_for :thumbnails, @prototype.thumbnails.main do |thumbnail|
            = thumbnail.file_field :image
            = thumbnail.hidden_field :status, value: :main
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :thumbnails, @prototype.thumbnails.sub do |thumbnail|
                = thumbnail.file_field :image
                = thumbnail.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload
              = f.fields_for :thumbnails, @prototype.thumbnails.sub do |thumbnail|
                = thumbnail.file_field :image
                = thumbnail.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        =f.text_field :catchcopy, placeholder: 'Catchcopy'
      .col-md-12
        =f.text_area :concept, placeholder: 'Concept'
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            %input{type: "text", placeholder: "TAG名"}/
          .col-md-3
            %input{type: "text", placeholder: "TAG名"}/
          .col-md-3
            %input{type: "text", placeholder: "TAG名"}/
    .row.text-center.proto-btn
      =f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/new.html.haml
= form_for @prototype, html: {class: 'container proto-new'} do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: 'proto-new-title'
    .row
      .col-md-12
        .cover-image-upload#upload-main
          = f.fields_for :thumbnails do |thumbnail|
            = thumbnail.file_field :image
            = thumbnail.hidden_field :status, value: :main
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload#upload-sub1
              = f.fields_for :thumbnails do |thumbnail|
                = thumbnail.file_field :image
                = thumbnail.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload#upload-sub2
              = f.fields_for :thumbnails do |thumbnail|
                = thumbnail.file_field :image
                = thumbnail.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: 'Catchcopy'
      .col-md-12
        = f.text_area :concept, placeholder: 'Concept'
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag 'prototype[tag][]','', placeholder: 'TAG名1'
            / %input{type: "text", placeholder: "TAG名"}/
          .col-md-3
            = text_field_tag 'prototype[tag][]','', placeholder: 'TAG名2'
            / %input{type: "text", placeholder: "TAG名"}/
          .col-md-3
            = text_field_tag 'prototype[tag][]','', placeholder: 'TAG名3'
            / %input{type: "text", placeholder: "TAG名"}/
    .row.text-center.proto-btn
      = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.sort_tab.popular{role: "presentation"}
          = link_to "Popular PROTO", prototypes_popular_index_path #, onclick: "this.class='inactive'"
        %li.sort_tab.newest.active{role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path #, onclick: "this.style.backgroundColor='#009900'"
      = link_to "View Tags", root_path, class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    = render partial: 'top/prototype', collection: @prototypes
.text-center
  = paginate @prototypes

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.sort_tab.popular.active{role: "presentation"}
          = link_to "Popular PROTO", prototypes_popular_index_path
        %li.sort_tab.newest{role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path
      = link_to "View Tags", root_path, class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    = render partial: 'top/prototype', collection: @prototypes
.text-center
  = paginate @prototypes

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          / = link_to image_tag(@prototype.user.avatar, alt: "64x64", class: "media-object", style: "width: 64px; height: 64px;", data: { src: "holder.js/64x64" }, data: { holder: { rendered: "true" } }), user_path(@prototype.user)
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to @prototype.user.name, prototypes_user_path(@prototype.user)
          %span.degree
            = @prototype.user.profile
    #like_box
      =render partial: 'likes/like'
    .row
      .col-md-9
        = link_to image_tag(@prototype.thumbnails.main.first.image), prototype_path(@prototype), class: "img-responsive"
      .col-md-3
        %ul.proto-sub-list.list-group
          %li.list-group-item
            = link_to image_tag(@prototype.thumbnails.sub.first.image), prototype_path(@prototype), class: "img-responsive"
          %li.list-group-item
            = link_to image_tag(@prototype.thumbnails.sub.first.image), prototype_path(@prototype), class: "img-responsive"
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: 'btn btn-default'
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (#{@prototype.comments.count})
    .col-md-8
      #comments
        = render partial: 'comments/comment', collection: @comments
      .form-inline
        = form_for @new_comment, remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :comment, class: "form-control", placeholder: "Your comments", rows: "3"
              = f.hidden_field :prototype_id, value: @prototype.id
            .form-group.col-md-2
              = f.submit :comment, class: "btn btn-primary", value: "Comment"

app/views/tags/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    - if prototype.thumbnails.main.present?
      = link_to image_tag(prototype.thumbnails.main.first.image), prototype_path(prototype)
    - else
      = link_to image_tag("no_img.png"), prototype_path(prototype)
    .caption
      %h3
        = link_to prototype.title, prototype_path(prototype)
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.name}", user_registration_path(prototype)
        .proto-posted
          = prototype.created_at
      %ul.proto-tag-list.list-inline
        - prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: 'btn btn-default'

app/views/tags/_tag.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to tag, tag_path(tag.name), type: 'button', class: "btn btn-tag", style: "width: 100%; height: 50px; font-size: 2rem; font-weight: 300; padding-bottom: 3px; color: #999; background-color: #eee;"
    .tag-meta
      %a{href: tag_path(tag.name), style: "display: block; font-size: 1.3rem; border-radius: 2px; margin: 0 -2px 2px;", class: "label label-default tag-list-number"}
        = tag.taggings_count
        %i Prototypes

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", prototypes_popular_index_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags
.container.proto-list
  .row
    = render partial: 'tag', collection: @tags

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", prototypes_popular_index_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags
.container
  .row
    .col-sm-12.proto-content
      .thumbnail
        = button_tag @tag, type: 'button', class: "btn btn-tag", style: "width: 100%; height: 50px; font-size: 2rem; font-weight: 300; padding-bottom: 3px; color: #999; background-color: #eee;"
        .tag-meta
          %a{href: tag_path(@tag), style: "display: block; font-size: 1.3rem; border-radius: 2px; margin: 0 -2px 2px;", class: "label label-default tag-list-number"}
            = @tag
            %i Protorypes
.container.proto-list
  .row
    = render partial: 'prototype', collection: @prototypes
.text-center
  = paginate @prototypes

app/views/top/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .dropdown.drop_menu_location
    - if user_signed_in? && prototype.user_id == current_user.id
      %div.dropdown
        %button.btn.btn-default.dropdown-toggle#dropdownMenu{'data-toggle' => 'dropdown', type: 'button'}
          Menu
        %ul.dropdown-menu{ 'aria-labelledby' => 'dropdownMenu1' }
          %li
            = link_to "Delete", "/prototypes/#{prototype.id}", method: :delete
          %li
            = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    - if prototype.thumbnails.main.present?
      = link_to image_tag(prototype.thumbnails.main.first.image), prototype_path(prototype)
    - else
      = link_to image_tag("no_img.png"), prototype_path(prototype)
    .caption
      %h3
        = link_to prototype.title, prototype_path(prototype)
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.name}", user_registration_path(prototype)
        .proto-posted
          = prototype.created_at
      %ul.proto-tag-list.list-inline
        %li
          = link_to "iPad", prototype_path(prototype), class: 'btn btn-default'

app/views/top/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.sort_tab.popular.active{role: "presentation"}
          = link_to "Popular PROTO", prototypes_popular_index_path #, onclick: "this.class='inactive'"
        %li.sort_tab.newest{role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path #, onclick: "this.style.backgroundColor='#009900'"
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    = render partial: 'top/prototype', collection: @prototypes
.text-center
  = paginate @prototypes

app/views/users/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    - if prototype.thumbnails.present?
      = link_to image_tag(prototype.thumbnails.main.first.image), prototype_path(prototype)
      .caption
        %h3
          = link_to prototype.title, prototype_path(prototype)
        .proto-meta
          .proto-date
            = prototype.updated_at
          .proto-user
            = link_to "by #{prototype.user.name}", user_registration_path(prototype)
          .proto-posted
            = prototype.created_at
        %ul.proto-tag-list.list-inline
          %li
            = link_to "iPad", prototype_path(prototype), class: 'btn btn-default'
    - else
      = link_to image_tag("no_img.png"), prototype_path(prototype)
      .caption
        %h3
          = link_to prototype.title, prototype_path(prototype)
        .proto-meta
          .proto-date
            = prototype.updated_at
          .proto-user
            = link_to "by #{prototype.user.name}", user_registration_path(prototype)
          .proto-posted
            = prototype.created_at
        %ul.proto-tag-list.list-inline
          %li
            = link_to "iPad", prototype_path(prototype), class: 'btn btn-default'

app/views/users/edit.html.haml
%form.container.user-new{:action => ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            %input{:type => "text", :placeholder => "Username", :value => "TECH::MASTER"}/
          .user-image.col-md-2{:style => 'background-image: url(http://泣ける動画.com/wp-content/uploads/2015/01/t0205-01.jpg);'}
            %button.btn.btn-primary Change image
            %input{:type => "file"}/
        %input.user-email{:type => "email", :placeholder => "E-Mail", :value => "wakatsuki@we-b.co.jp"}/
        %input.user-password{:type => "password", :placeholder => "Password"}/
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            %input{:type => "text", :placeholder => "Member", :value => "we-b inc."}/
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            %textarea{:name => "textarea", :cols => "30", :rows => "4", :placeholder => "Profile"}
              I designer. I'm working with we-b inc.
              I believe the everyday Web and UI / UX.
              My hobby is collecting cassette tape.
              Thank you very much in advance.
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            %textarea{:name => "textarea", :cols => "30", :rows => "4", :placeholder => "Works"}
              2012 Sakura Internet inc. Designer
              2012 we-b inc. Designer
              2012 Life is Tech. Mentor
              2014 Cookpad inc. Designer
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Save

app/views/users/new.html.haml
%form.container.user-new{:action => ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Register
        .user-name_image.row
          .user-name.col-md-10
            %input{:type => "text", :placeholder => "Username"}/
          .user-image.col-md-2
            %button.btn.btn-primary Add image
            %input{:type => "file"}/
        %input.user-email{:type => "email", :placeholder => "E-Mail"}/
        %input.user-password{:type => "password", :placeholder => "Password"}/
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            %input{:type => "text", :placeholder => "Member"}/
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            %textarea{:name => "textarea", :cols => "30", :rows => "4", :placeholder => "Profile"}
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            %textarea{:name => "textarea", :cols => "30", :rows => "4", :placeholder => "Works"}
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Save

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        - if @user.avatar?
          = image_tag(@user.avatar, alt: "64*64", class: "media-object", style: "width: 64px; height: 64px;", data:{ src: "holder.js/64x64" }, data:{ holder:{ rendered: "true"} })
        - else
          = image_tag "no_img.png"
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.works
.container.proto-list
  .row
    = render partial: 'users/prototype', collection: @prototypes
.text-center
  = paginate @prototypes

app/views/users/sign_in.html.haml
.container
  %form.form-signin
    %h2.form-signin-heading Please sign in
    %label.sr-only{:for => "inputEmail"} Email address
    %input#inputEmail.form-control{:autofocus => "", :placeholder => "Email address", :required => "", :type => "email"}/
    %label.sr-only{:for => "inputPassword"} Password
    %input#inputPassword.form-control{:placeholder => "Password", :required => "", :type => "password"}/
    .checkbox
      %label
        %input{:type => "checkbox", :value => "remember-me"}/
        Remember me
    %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Sign in
  .text-center
    %p
      Not a member?
      %a{:href => "/users/new"} Sign up now